
spring.application.name=ProfileMS

server.port=9100

# spring.datasource.url=jdbc:mysql://localhost:3306/profiledb
# spring.datasource.username=root
# spring.datasource.password=Tarun@12
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:profiledb}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Tarun@12}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Configuration for Docker/Cloud
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

 DOCTOR_NOT_FOUND="Doctor not found"
DOCTOR_ALREADY_EXIST="Doctor already exists"
PATIENT_ALREADY_EXISTS = "Patient already exist"
PATIENT_NOT_FOUND = "Patient not found"


# prometheus configs
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true