server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;   # telling the nginx the location of built react file
        index  index.html;
        try_files $uri /index.html;
    }
}