spring.application.name=PharmacyMS

server.port=9300

# spring.datasource.url=jdbc:mysql://localhost:3306/pharmacydb
# spring.datasource.username=root
# spring.datasource.password=Tarun@12
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:pharmacydb}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Tarun@12}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Configuration for Docker/Cloud
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

MEDICINE_ALREADY_EXISTS=Medicine with the same name and dosage already exists.
MEDICINE_NOT_FOUND=Medicine not found
OUT_OF_STOCK=Medicine is out of stock
INVALID_QUANTITY=Requested quantity exceeds available stock
SALE_NOT_FOUND=Sale record not found
INVALID_SALE_QUANTITY=Sale quantity must be greater than zero
SALE_ALREADY_EXISTS=Sale already exists for the given prescription id

# prometheus configs
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true

