spring.application.name=UserMS
server.port=8080

# spring.datasource.url=jdbc:mysql://localhost:3306/hms
# spring.datasource.username=root
# spring.datasource.password=Tarun@12
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:hms}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Tarun@12}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Configuration for Docker/Cloud
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

USER_ALREADY_EXIST= User already exist
INVALID_CREDENTIALS= Invalid credentials
USER_NOT_FOUND=User not found

# prometheus configs
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true